"""PostgreSQL query encoding for the LikeApx comparison.

The sampled values are generated by PostgreSQL and shared with the MCDB
comparison. This module converts those values to rows of the form
``(attribute, marked_null, repair_index, sampled_value)`` and evaluates the
input query over the repair-indexed relation in PostgreSQL.
"""

from __future__ import annotations

import dataclasses
import os
import time
from typing import Dict, Mapping, Optional, Sequence, Tuple

from MCDBPostgresNative import (
    BundleRelation,
    NativeMCDB,
    QueryResult,
    QuerySpec,
    _clean_name,
    _temp_name,
    literal,
    parse_query,
    qident,
)


@dataclasses.dataclass
class LikeApxRelation:
    base_table: str
    assignment_table: str
    h: int
    columns: Tuple[str, ...]
    column_types: Dict[str, str]
    missing_attributes: Tuple[str, ...]
    encoding_s: float

    def has_column(self, column: str) -> bool:
        return column.lower() in self.column_types

    def is_random(self, column: str) -> bool:
        return column.lower() in self.missing_attributes


class NativeLikeApx:
    def __init__(self, engine: NativeMCDB):
        self.engine = engine
        self.connection = engine.connection

    def create_relation(self, bundle: BundleRelation,
                        prefix: Optional[str] = None) -> LikeApxRelation:
        prefix = prefix or _temp_name("likeapx", bundle.base_table, str(bundle.h))
        assignment_table = _temp_name(prefix, "assignments")
        cursor = self.connection.cursor()
        started = time.perf_counter()
        cursor.execute("DROP TABLE IF EXISTS %s" % qident(assignment_table))
        cursor.execute(
            "CREATE TEMP TABLE %s ("
            "attribute text NOT NULL, symbol text NOT NULL, "
            "idx integer NOT NULL, sampled_value text NOT NULL"
            ") ON COMMIT PRESERVE ROWS" % qident(assignment_table)
        )
        for attribute, sample_table in bundle.sample_tables.items():
            cursor.execute(
                "INSERT INTO %s (attribute, symbol, idx, sampled_value) "
                "SELECT %s, s.symbol, u.idx::integer, u.sampled_value::text "
                "FROM %s s "
                "CROSS JOIN LATERAL unnest(s.samples) WITH ORDINALITY "
                "AS u(sampled_value, idx)" % (
                    qident(assignment_table), literal(attribute),
                    qident(sample_table),
                )
            )
        cursor.execute(
            "CREATE UNIQUE INDEX ON %s (attribute, symbol, idx)" %
            qident(assignment_table)
        )
        cursor.execute("ANALYZE %s" % qident(assignment_table))
        self.connection.commit()
        encoding_s = time.perf_counter() - started
        return LikeApxRelation(
            base_table=bundle.base_table,
            assignment_table=assignment_table,
            h=bundle.h,
            columns=bundle.columns,
            column_types=bundle.column_types,
            missing_attributes=bundle.missing_attributes,
            encoding_s=encoding_s,
        )

    @staticmethod
    def _resolve_relation(token: str,
                          relations: Mapping[str, LikeApxRelation]) -> LikeApxRelation:
        options = (
            token,
            os.path.basename(token),
            token.lower(),
            os.path.basename(token).lower(),
        )
        for option in options:
            if option in relations:
                return relations[option]
        raise KeyError("No LikeApx relation supplied for %s" % token)

    @staticmethod
    def _cast_assignment(alias: str, type_name: str) -> str:
        return "%s.sampled_value::%s" % (alias, type_name)

    def _expanded_cte(self, name: str, relation: LikeApxRelation,
                      alias: str, needed: Sequence[str]) -> str:
        joins = []
        values = []
        for column in needed:
            if relation.is_random(column):
                assignment_alias = "a_%s_%s" % (alias, _clean_name(column))
                symbol = NativeMCDB._symbol_expression(alias, column, relation.columns)
                joins.append(
                    "LEFT JOIN %s %s ON %s.attribute = %s "
                    "AND %s.symbol = %s AND %s.idx = g.idx" % (
                        qident(relation.assignment_table), assignment_alias,
                        assignment_alias, literal(column), assignment_alias,
                        symbol, assignment_alias,
                    )
                )
                expression = "COALESCE(%s.%s, %s)" % (
                    alias, qident(column),
                    self._cast_assignment(
                        assignment_alias, relation.column_types[column]
                    ),
                )
            else:
                expression = "%s.%s" % (alias, qident(column))
            values.append("%s AS %s" % (expression, qident(column)))
        suffix = ", " + ", ".join(values) if values else ""
        return (
            "%s AS (SELECT g.idx, %s.%s AS rid%s FROM %s %s "
            "CROSS JOIN generate_series(1, %d) AS g(idx) %s)" % (
                name, alias, qident("_rid"), suffix,
                qident(relation.base_table), alias, relation.h, " ".join(joins),
            )
        )

    def compile(self, query: str,
                relations: Mapping[str, LikeApxRelation]):
        spec = parse_query(query)
        left = self._resolve_relation(spec.left_token, relations)
        right = self._resolve_relation(spec.right_token, relations) \
            if spec.right_token else None
        needed = self.engine._needed_columns(spec)
        left_columns = [column for column in needed if left.has_column(column)]
        if spec.join_column and spec.join_column not in left_columns:
            left_columns.append(spec.join_column)
        ctes = [self._expanded_cte("likeapx_left", left, "lb", left_columns)]

        if right:
            if left.h != right.h:
                raise ValueError("LikeApx relations must use the same H")
            right_columns = [column for column in needed if right.has_column(column)]
            if spec.join_column and spec.join_column not in right_columns:
                right_columns.append(spec.join_column)
            ctes.append(
                self._expanded_cte("likeapx_right", right, "rb", right_columns)
            )
            values = []
            for column in needed:
                source = self.engine._column_source(
                    column, left, right, spec.join_column
                )
                values.append("%s.%s AS %s" % (
                    source, qident(column), qident(column),
                ))
            suffix = ", " + ", ".join(values) if values else ""
            ctes.append(
                "world_rows AS (SELECT l.idx%s FROM likeapx_left l "
                "JOIN likeapx_right r ON l.idx = r.idx "
                "AND l.%s = r.%s)" % (
                    suffix, qident(spec.join_column or ""),
                    qident(spec.join_column or ""),
                )
            )
        else:
            selections = ", ".join(
                "l.%s AS %s" % (qident(column), qident(column))
                for column in needed
            )
            suffix = ", " + selections if selections else ""
            ctes.append(
                "world_rows AS (SELECT l.idx%s FROM likeapx_left l)" % suffix
            )

        answer_cte, output_columns = self.engine._answer_cte(spec, "world_rows")
        ctes.append(answer_cte)
        summary_sql, summary_columns = self.engine._summary_sql(
            spec, output_columns, left.h
        )
        sql = "WITH " + ",\n".join(ctes) + " " + summary_sql
        return spec, sql, summary_columns

    def evaluate_summary(self, query: str,
                         relations: Mapping[str, LikeApxRelation]) -> QueryResult:
        spec, sql, summary_columns = self.compile(query, relations)
        cursor = self.connection.cursor()
        started = time.perf_counter()
        cursor.execute(sql)
        rows = cursor.fetchall()
        elapsed = time.perf_counter() - started
        return QueryResult(
            query=spec,
            world_rows=[],
            summary_rows=rows,
            world_columns=tuple(),
            summary_columns=summary_columns,
            sql=sql,
            elapsed_s=elapsed,
        )


def relation_mapping(relation: LikeApxRelation,
                     *tokens: str) -> Dict[str, LikeApxRelation]:
    result = {relation.base_table: relation}
    for token in tokens:
        result[token] = relation
        result[os.path.basename(token)] = relation
        result[token.lower()] = relation
        result[os.path.basename(token).lower()] = relation
    return result


__all__ = ["LikeApxRelation", "NativeLikeApx", "relation_mapping"]
